appname = travel-sphere
httpport = 8080
runmode = dev

sessionon = true

REST_COUNTRIES_BASE_URL = https://api.restcountries.com/countries/v5
REST_COUNTRIES_API_KEY =
OPENTRIPMAP_BASE_URL = https://api.opentripmap.com/0.1/en/places
OPENTRIPMAP_API_KEY =

DEMO_USERNAME = user
DEMO_PASSWORD = admin
